<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipelin2523182022/blob/main/notebooks/ETL_Notas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipelin2523182022/refs/heads/main/data/raw/A_notas.csv"
df = pd.read_csv(url)
df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

In [3]:
#explorar archivos
df.shape
df.info()
df.isnull().sum()
print("Exploración de notas completada.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_nota        330 non-null    object
 1   id_estudiante  325 non-null    object
 2   id_curso       328 non-null    object
 3   nota           326 non-null    object
 4   periodo        330 non-null    object
dtypes: object(5)
memory usage: 13.0+ KB
Exploración de notas completada.

In [4]:
#limpieza datos
notas = df.copy()
notas.columns = notas.columns.str.strip().str.lower()

# Convertir nota a número (esto vuelve NaN a la palabra "diez" y a los vacíos)
notas['nota'] = pd.to_numeric(notas['nota'], errors='coerce')

for col in notas.select_dtypes(include='object').columns:
    notas[col] = notas[col].astype(str).str.strip()

notas = notas.replace(['nan', 'None', ''], pd.NA)
notas = notas.replace(r'^\s*$', pd.NA, regex=True)
notas = notas.drop_duplicates()
print(" Limpieza de notas completada.")

 Limpieza de notas completada.

In [6]:
#separar datos validos y rechazados
columnas_obligatorias = ['id_estudiante', 'id_curso', 'nota']

validos = notas[notas[columnas_obligatorias].notna().all(axis=1)].copy()
rechazados = notas[notas[columnas_obligatorias].isna().any(axis=1)].copy()
print(f" Separación de notas finalizada. Válidos: {len(validos)}, Rechazados: {len(rechazados)}")

 Separación de notas finalizada. Válidos: 287, Rechazados: 33

In [8]:
#motivo rechazo
def motivo_not(row):
    motivos = []
    if pd.isna(row['id_estudiante']): motivos.append("id_estudiante_vacio")
    if pd.isna(row['id_curso']): motivos.append("id_curso_vacio")
    if pd.isna(row['nota']): motivos.append("nota_invalida_o_vacia")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_not, axis=1)

In [10]:
#exportar archivos
validos.to_csv("notas_curated.csv", index=False)
rechazados.to_csv("notas_rejects.csv", index=False)
print(" Archivos de notas exportados.")

 Archivos de notas exportados.

In [11]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 22.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [13]:
#cargar datos en postgresql
validos.to_sql('notas_curated', engine, if_exists='append', index=False)
rechazados.to_sql('notas_rejects', engine, if_exists='append', index=False)
print(" Carga de notas a Render completada.")

 Carga de notas a Render completada.

In [14]:
#validar carga
pd.read_sql("SELECT * FROM notas_curated", engine)

    id_nota id_estudiante id_curso  nota  periodo
0     N5000         E1102     C204   7.9   I-2025
1     N5001         E1179     C205   8.1   I-2025
2     N5002         E1092     C202   8.6   I-2025
3     N5003         E1014     C211   8.0   I-2025
4     N5004         E1106     C208   7.4  II-2025
..      ...           ...      ...   ...      ...
569   N5314         E1003     C202   6.8   I-2025
570   N5315         E1034     C206   6.0   I-2025
571   N5316         E1048     C202   6.3  II-2025
572   N5318         E1171     C211   5.3  II-2025
573   N5319         E1157     C209   8.2   I-2025

[574 rows x 5 columns]